imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        console:
            type: console
            process_psr_3_messages: false

parameters:
    # database details
    database_host:     docker-symfony-test.cl0ms7kqptss.ap-southeast-2.rds.amazonaws.com
    database_port:     3306
    dbname:            dockersymfony
    database_name:     dockersymfony
    database_password: dockersymfony